Feature/entities
Al2lo/Practice_Shop pull request #3
Opened 2024-06-26 09:24 UTC by IlyaSkachko

2024-06-26 09:29 UTC, Elizaveta564 requested changes

2024-06-26 09:29 UTC, Elizaveta564 commented on Practice_Shop/PracticeShop.DAL/Entities/Category.cs
> +        public Guid Guid { get; set; }
it is better to call it 'Id'

2024-06-26 09:29 UTC, Elizaveta564 commented on Practice_Shop/PracticeShop.DAL/Entities/Category.cs
> +        public Guid Guid { get; set; }
and why do you decide to use Guid?

2024-06-26 09:29 UTC, Elizaveta564 commented on Practice_Shop/PracticeShop.DAL/Entities/Order.cs
> +        public Guid User_Id { get; set; }
You should use camel case, not snake

2024-06-26 09:42 UTC, IlyaSkachko commented on Practice_Shop/PracticeShop.DAL/Entities/Category.cs
> +        public Guid Guid { get; set; }
low possibility of repetition

2024-06-27 13:11 UTC, Elizaveta564 approved these changes

2024-06-27 13:22 UTC, merged